//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace osadniciZKatanu.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("osadniciZKatanu.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;faces&gt;
        ///  &lt;face xCoord=&quot;296&quot; yCoord=&quot;81&quot;&gt;
        ///    &lt;material&gt;grain&lt;/material&gt;
        ///    &lt;number&gt;4&lt;/number&gt;
        ///  &lt;/face&gt;
        ///  &lt;face xCoord=&quot;211.2&quot; yCoord=&quot;129.8&quot;&gt;
        ///    &lt;material&gt;brick&lt;/material&gt;
        ///    &lt;number&gt;2&lt;/number&gt;
        ///  &lt;/face&gt; 
        ///  &lt;face xCoord=&quot;380.8&quot; yCoord=&quot;129.8&quot;&gt;
        ///    &lt;material&gt;wood&lt;/material&gt;
        ///    &lt;number&gt;6&lt;/number&gt;
        ///  &lt;/face&gt; 
        ///  &lt;face xCoord=&quot;127.2&quot; yCoord=&quot;178.6&quot;&gt;
        ///    &lt;material&gt;sheep&lt;/material&gt;
        ///    &lt;number&gt;9&lt;/number&gt;
        ///  &lt;/face&gt; 
        ///  &lt;face xCoord=&quot;296&quot; yCoord=&quot;178.6&quot;&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string faces {
            get {
                return ResourceManager.GetString("faces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;game pointsToWin=&quot;10&quot; longestRoad=&quot;4&quot; largestArmy=&quot;2&quot; villageProduction=&quot;1&quot; townProduction=&quot;2&quot; longestRoadProduction=&quot;2&quot; largestArmyProduction=&quot;2&quot;&gt;
        ///  &lt;actionCardPackage&gt;
        ///    &lt;knight count=&quot;14&quot;&gt;&lt;/knight&gt;
        ///    &lt;coupon count=&quot;5&quot;&gt;&lt;/coupon&gt;
        ///    &lt;materialFromPlayers count=&quot;2&quot;&gt;&lt;/materialFromPlayers&gt;
        ///    &lt;twoMaterials count=&quot;2&quot;&gt;&lt;/twoMaterials&gt;
        ///    &lt;twoRoad count=&quot;2&quot;&gt;&lt;/twoRoad&gt;
        ///  &lt;/actionCardPackage&gt;
        ///  &lt;ports&gt;
        ///    &lt;specialPort rate=&quot;2&quot;&gt;&lt;/specialPort&gt;
        ///    &lt;universalP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string game {
            get {
                return ResourceManager.GetString("game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;player roadCount=&quot;15&quot; villageCount=&quot;5&quot; townCount=&quot;4&quot;&gt;&lt;/player&gt;.
        /// </summary>
        internal static string player {
            get {
                return ResourceManager.GetString("player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ports&gt;
        ///  &lt;port xCoord=&quot;267.2&quot; yCoord=&quot;32.2&quot;&gt;
        ///    &lt;material&gt;noMaterial&lt;/material&gt;
        ///  &lt;/port&gt;
        ///  &lt;port xCoord=&quot;324.8&quot; yCoord=&quot;32.2&quot;&gt;
        ///    &lt;material&gt;noMaterial&lt;/material&gt;
        ///  &lt;/port&gt;
        ///  &lt;port xCoord=&quot;408.8&quot; yCoord=&quot;81&quot;&gt;
        ///    &lt;material&gt;sheep&lt;/material&gt;
        ///  &lt;/port&gt;
        ///  &lt;port xCoord=&quot;436.8&quot; yCoord=&quot;129.8&quot;&gt;
        ///    &lt;material&gt;sheep&lt;/material&gt;
        ///  &lt;/port&gt;
        ///  &lt;port xCoord=&quot;521.6&quot; yCoord=&quot;178.6&quot;&gt;
        ///    &lt;material&gt;noMaterial&lt;/material&gt;
        ///  &lt;/port&gt;
        ///  &lt;port xCoord=&quot;493.6&quot; yCoord=&quot;227.4&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ports {
            get {
                return ResourceManager.GetString("ports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;vertices&gt;
        ///  &lt;vertex xCoord=&quot;267.2&quot; yCoord=&quot;32.2&quot;&gt;&lt;/vertex&gt;
        ///  &lt;vertex xCoord=&quot;324.8&quot; yCoord=&quot;32.2&quot;&gt;&lt;/vertex&gt;
        ///  &lt;vertex xCoord=&quot;182.4&quot; yCoord=&quot;81&quot;&gt;&lt;/vertex&gt;
        ///  &lt;vertex xCoord=&quot;239.2&quot; yCoord=&quot;81&quot;&gt;&lt;/vertex&gt;
        ///  &lt;vertex xCoord=&quot;352&quot; yCoord=&quot;81&quot;&gt;&lt;/vertex&gt;
        ///  &lt;vertex xCoord=&quot;408.8&quot; yCoord=&quot;81&quot;&gt;&lt;/vertex&gt;
        ///  &lt;vertex xCoord=&quot;98.4&quot; yCoord=&quot;129.8&quot;&gt;&lt;/vertex&gt;
        ///  &lt;vertex xCoord=&quot;154.4&quot; yCoord=&quot;129.8&quot;&gt;&lt;/vertex&gt;
        ///  &lt;vertex xCoord=&quot;267.2&quot; yCoord=&quot;129.8&quot;&gt;&lt;/vertex&gt;
        ///  &lt;vertex xCoord= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vertices {
            get {
                return ResourceManager.GetString("vertices", resourceCulture);
            }
        }
    }
}
